name: Build & Release

on:
  push:
    branches: [main]
    paths-ignore: .github/**
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate version string
        id: versionstrings
        run: echo "plugin_version=$(perl -n -e'/^Version:\s*(\d+.\d+.\d+)/ && print $1' style.css)" >> $GITHUB_OUTPUT
      - name: Check if version strings are set
        if: ${{ !steps.versionstrings.outputs.plugin_version}}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Plugin version not set')

      - name: Create a .npmrc file for the github private repository
        run: |
          echo "${{ secrets.NPMRC }}" >> .npmrc
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: true
      - name: build
        run: |
          pnpm run bundle
      - uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          tag_name: ${{ steps.versionstrings.outputs.plugin_version}}
          name: ${{ steps.versionstrings.outputs.plugin_version}}
          draft: false
          prerelease: false
          files: ./bundle/*.zip
