name: Version Check

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    
jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - name: Generate version strings
        id: versionstrings
        run: |
          echo "::set-output name=plugin_version::$(perl -n -e'/^Version:\s*(\d.\d.\d)/ && print $1' style.css)"
          PACKAGE_JSON_VERSION=$(npm pkg get version | sed 's/"//g')
          echo "Version: $PACKAGE_VERSION"
          echo "::set-output name=package_json_version::$PACKAGE_JSON_VERSION"
      - name: Check if version strings are set
        if: ${{ !steps.versionstrings.outputs.plugin_version || !steps.versionstrings.outputs.package_json_version}}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Version strings not set')
      - name: Check if version strings are equal
        if: ${{steps.versionstrings.outputs.plugin_version != steps.versionstrings.outputs.package_json_version}}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Version strings are not equal')
      - name: Get latest tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Get possible next versions
        id: nexttags
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Validate versions
        if:  ${{ steps.nexttags.outputs.major != steps.versionstrings.outputs.plugin_version && steps.nexttags.outputs.minor != steps.versionstrings.outputs.plugin_version && steps.nexttags.outputs.patch != steps.versionstrings.outputs.plugin_version }} 
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Invalid version')
